---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches:
      - main
    paths:
      - apps/**
  workflow_dispatch:
    inputs:
      app:
        type: string
        description: App Name
        required: true

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get changed files (push)
        uses: https://github.com/bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        id: changed-files-action
        if: ${{ forgejo.event_name == 'push' }}
        with:
          path: apps
          include_only_directories: true
          max_depth: 1

      - name: Set changed files output
        id: changed-files
        run: |
          if [ "${{ forgejo.event_name }}" = "workflow_dispatch" ]; then
            echo 'changed_files=["${{ inputs.app }}"]' >> $FORGEJO_OUTPUT
          else
            echo 'changed_files=${{ steps.changed-files-action.outputs.changed_files }}' >> $FORGEJO_OUTPUT
          fi

  build:
    if: ${{ needs.prepare.outputs.changed-files != '[]' && needs.prepare.outputs.changed-files != '' }}
    name: Build ${{ matrix.app }}
    needs:
      - prepare
    strategy:
      matrix:
        app: ${{ fromJSON(needs.prepare.outputs.changed-files) }}
      fail-fast: false
      max-parallel: 2
    uses: ./.forgejo/workflows/app-builder.yaml
    secrets: inherit
    with:
      app: ${{ matrix.app }}
      release: true

  status:
    if: ${{ !cancelled() }}
    name: Build Success
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !contains(needs.*.result, 'failure') }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
